//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("DOCMGModel", "TBFIELD_RL_USER_FIELD_FK1", "TBFIELD", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DocumentManager.Web.TBFIELD), "RL_USER_FIELD", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DocumentManager.Web.RL_USER_FIELD), true)]
[assembly: EdmRelationshipAttribute("DOCMGModel", "TBUSER_RL_USER_FIELD_FK1", "TBUSER", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DocumentManager.Web.TBUSER), "RL_USER_FIELD", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DocumentManager.Web.RL_USER_FIELD), true)]
[assembly: EdmRelationshipAttribute("DOCMGModel", "TBSYSCODETYPE_TBSYSCODE_FK1", "TBSYSCODETYPE", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DocumentManager.Web.TBSYSCODETYPE), "TBSYSCODE", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DocumentManager.Web.TBSYSCODE), true)]
[assembly: EdmRelationshipAttribute("DOCMGModel", "RL_USER_MODULE", "TBMODULE", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DocumentManager.Web.TBMODULE), "TBUSER", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DocumentManager.Web.TBUSER))]

#endregion

namespace DocumentManager.Web
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class DOCMGEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“DOCMGEntities”部分中的连接字符串初始化新 DOCMGEntities 对象。
        /// </summary>
        public DOCMGEntities() : base("name=DOCMGEntities", "DOCMGEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 DOCMGEntities 对象。
        /// </summary>
        public DOCMGEntities(string connectionString) : base(connectionString, "DOCMGEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 DOCMGEntities 对象。
        /// </summary>
        public DOCMGEntities(EntityConnection connection) : base(connection, "DOCMGEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<RL_USER_FIELD> RL_USER_FIELD
        {
            get
            {
                if ((_RL_USER_FIELD == null))
                {
                    _RL_USER_FIELD = base.CreateObjectSet<RL_USER_FIELD>("RL_USER_FIELD");
                }
                return _RL_USER_FIELD;
            }
        }
        private ObjectSet<RL_USER_FIELD> _RL_USER_FIELD;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<TBCONTRACT> TBCONTRACT
        {
            get
            {
                if ((_TBCONTRACT == null))
                {
                    _TBCONTRACT = base.CreateObjectSet<TBCONTRACT>("TBCONTRACT");
                }
                return _TBCONTRACT;
            }
        }
        private ObjectSet<TBCONTRACT> _TBCONTRACT;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<TBFIELD> TBFIELD
        {
            get
            {
                if ((_TBFIELD == null))
                {
                    _TBFIELD = base.CreateObjectSet<TBFIELD>("TBFIELD");
                }
                return _TBFIELD;
            }
        }
        private ObjectSet<TBFIELD> _TBFIELD;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<TBMODULE> TBMODULE
        {
            get
            {
                if ((_TBMODULE == null))
                {
                    _TBMODULE = base.CreateObjectSet<TBMODULE>("TBMODULE");
                }
                return _TBMODULE;
            }
        }
        private ObjectSet<TBMODULE> _TBMODULE;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<TBSYSCODE> TBSYSCODE
        {
            get
            {
                if ((_TBSYSCODE == null))
                {
                    _TBSYSCODE = base.CreateObjectSet<TBSYSCODE>("TBSYSCODE");
                }
                return _TBSYSCODE;
            }
        }
        private ObjectSet<TBSYSCODE> _TBSYSCODE;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<TBSYSCODETYPE> TBSYSCODETYPE
        {
            get
            {
                if ((_TBSYSCODETYPE == null))
                {
                    _TBSYSCODETYPE = base.CreateObjectSet<TBSYSCODETYPE>("TBSYSCODETYPE");
                }
                return _TBSYSCODETYPE;
            }
        }
        private ObjectSet<TBSYSCODETYPE> _TBSYSCODETYPE;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<TBUSER> TBUSER
        {
            get
            {
                if ((_TBUSER == null))
                {
                    _TBUSER = base.CreateObjectSet<TBUSER>("TBUSER");
                }
                return _TBUSER;
            }
        }
        private ObjectSet<TBUSER> _TBUSER;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 RL_USER_FIELD EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToRL_USER_FIELD(RL_USER_FIELD rL_USER_FIELD)
        {
            base.AddObject("RL_USER_FIELD", rL_USER_FIELD);
        }
    
        /// <summary>
        /// 用于向 TBCONTRACT EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToTBCONTRACT(TBCONTRACT tBCONTRACT)
        {
            base.AddObject("TBCONTRACT", tBCONTRACT);
        }
    
        /// <summary>
        /// 用于向 TBFIELD EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToTBFIELD(TBFIELD tBFIELD)
        {
            base.AddObject("TBFIELD", tBFIELD);
        }
    
        /// <summary>
        /// 用于向 TBMODULE EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToTBMODULE(TBMODULE tBMODULE)
        {
            base.AddObject("TBMODULE", tBMODULE);
        }
    
        /// <summary>
        /// 用于向 TBSYSCODE EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToTBSYSCODE(TBSYSCODE tBSYSCODE)
        {
            base.AddObject("TBSYSCODE", tBSYSCODE);
        }
    
        /// <summary>
        /// 用于向 TBSYSCODETYPE EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToTBSYSCODETYPE(TBSYSCODETYPE tBSYSCODETYPE)
        {
            base.AddObject("TBSYSCODETYPE", tBSYSCODETYPE);
        }
    
        /// <summary>
        /// 用于向 TBUSER EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToTBUSER(TBUSER tBUSER)
        {
            base.AddObject("TBUSER", tBUSER);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DOCMGModel", Name="RL_USER_FIELD")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RL_USER_FIELD : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 RL_USER_FIELD 对象。
        /// </summary>
        /// <param name="uSERID">USERID 属性的初始值。</param>
        /// <param name="fIELDID">FIELDID 属性的初始值。</param>
        public static RL_USER_FIELD CreateRL_USER_FIELD(global::System.Int32 uSERID, global::System.Int32 fIELDID)
        {
            RL_USER_FIELD rL_USER_FIELD = new RL_USER_FIELD();
            rL_USER_FIELD.USERID = uSERID;
            rL_USER_FIELD.FIELDID = fIELDID;
            return rL_USER_FIELD;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 USERID
        {
            get
            {
                return _USERID;
            }
            set
            {
                if (_USERID != value)
                {
                    OnUSERIDChanging(value);
                    ReportPropertyChanging("USERID");
                    _USERID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("USERID");
                    OnUSERIDChanged();
                }
            }
        }
        private global::System.Int32 _USERID;
        partial void OnUSERIDChanging(global::System.Int32 value);
        partial void OnUSERIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FIELDID
        {
            get
            {
                return _FIELDID;
            }
            set
            {
                if (_FIELDID != value)
                {
                    OnFIELDIDChanging(value);
                    ReportPropertyChanging("FIELDID");
                    _FIELDID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FIELDID");
                    OnFIELDIDChanged();
                }
            }
        }
        private global::System.Int32 _FIELDID;
        partial void OnFIELDIDChanging(global::System.Int32 value);
        partial void OnFIELDIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AUTHTYPE
        {
            get
            {
                return _AUTHTYPE;
            }
            set
            {
                OnAUTHTYPEChanging(value);
                ReportPropertyChanging("AUTHTYPE");
                _AUTHTYPE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AUTHTYPE");
                OnAUTHTYPEChanged();
            }
        }
        private Nullable<global::System.Int32> _AUTHTYPE;
        partial void OnAUTHTYPEChanging(Nullable<global::System.Int32> value);
        partial void OnAUTHTYPEChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DOCMGModel", "TBFIELD_RL_USER_FIELD_FK1", "TBFIELD")]
        public TBFIELD TBFIELD
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBFIELD>("DOCMGModel.TBFIELD_RL_USER_FIELD_FK1", "TBFIELD").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBFIELD>("DOCMGModel.TBFIELD_RL_USER_FIELD_FK1", "TBFIELD").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TBFIELD> TBFIELDReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBFIELD>("DOCMGModel.TBFIELD_RL_USER_FIELD_FK1", "TBFIELD");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TBFIELD>("DOCMGModel.TBFIELD_RL_USER_FIELD_FK1", "TBFIELD", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DOCMGModel", "TBUSER_RL_USER_FIELD_FK1", "TBUSER")]
        public TBUSER TBUSER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBUSER>("DOCMGModel.TBUSER_RL_USER_FIELD_FK1", "TBUSER").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBUSER>("DOCMGModel.TBUSER_RL_USER_FIELD_FK1", "TBUSER").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TBUSER> TBUSERReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBUSER>("DOCMGModel.TBUSER_RL_USER_FIELD_FK1", "TBUSER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TBUSER>("DOCMGModel.TBUSER_RL_USER_FIELD_FK1", "TBUSER", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DOCMGModel", Name="TBCONTRACT")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBCONTRACT : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 TBCONTRACT 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static TBCONTRACT CreateTBCONTRACT(global::System.Int32 id)
        {
            TBCONTRACT tBCONTRACT = new TBCONTRACT();
            tBCONTRACT.ID = id;
            return tBCONTRACT;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DOCMGModel", Name="TBFIELD")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBFIELD : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 TBFIELD 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="tABLENAME">TABLENAME 属性的初始值。</param>
        public static TBFIELD CreateTBFIELD(global::System.Int32 id, global::System.String tABLENAME)
        {
            TBFIELD tBFIELD = new TBFIELD();
            tBFIELD.ID = id;
            tBFIELD.TABLENAME = tABLENAME;
            return tBFIELD;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TABLENAME
        {
            get
            {
                return _TABLENAME;
            }
            set
            {
                OnTABLENAMEChanging(value);
                ReportPropertyChanging("TABLENAME");
                _TABLENAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TABLENAME");
                OnTABLENAMEChanged();
            }
        }
        private global::System.String _TABLENAME;
        partial void OnTABLENAMEChanging(global::System.String value);
        partial void OnTABLENAMEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FIELDNAME
        {
            get
            {
                return _FIELDNAME;
            }
            set
            {
                OnFIELDNAMEChanging(value);
                ReportPropertyChanging("FIELDNAME");
                _FIELDNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FIELDNAME");
                OnFIELDNAMEChanged();
            }
        }
        private global::System.String _FIELDNAME;
        partial void OnFIELDNAMEChanging(global::System.String value);
        partial void OnFIELDNAMEChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DOCMGModel", "TBFIELD_RL_USER_FIELD_FK1", "RL_USER_FIELD")]
        public EntityCollection<RL_USER_FIELD> RL_USER_FIELD
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RL_USER_FIELD>("DOCMGModel.TBFIELD_RL_USER_FIELD_FK1", "RL_USER_FIELD");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RL_USER_FIELD>("DOCMGModel.TBFIELD_RL_USER_FIELD_FK1", "RL_USER_FIELD", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DOCMGModel", Name="TBMODULE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBMODULE : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 TBMODULE 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="nAME">NAME 属性的初始值。</param>
        /// <param name="mODULEPATH">MODULEPATH 属性的初始值。</param>
        /// <param name="oRDERINDEX">ORDERINDEX 属性的初始值。</param>
        public static TBMODULE CreateTBMODULE(global::System.Int32 id, global::System.String nAME, global::System.String mODULEPATH, global::System.Int32 oRDERINDEX)
        {
            TBMODULE tBMODULE = new TBMODULE();
            tBMODULE.ID = id;
            tBMODULE.NAME = nAME;
            tBMODULE.MODULEPATH = mODULEPATH;
            tBMODULE.ORDERINDEX = oRDERINDEX;
            return tBMODULE;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MODULEPATH
        {
            get
            {
                return _MODULEPATH;
            }
            set
            {
                OnMODULEPATHChanging(value);
                ReportPropertyChanging("MODULEPATH");
                _MODULEPATH = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MODULEPATH");
                OnMODULEPATHChanged();
            }
        }
        private global::System.String _MODULEPATH;
        partial void OnMODULEPATHChanging(global::System.String value);
        partial void OnMODULEPATHChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ORDERINDEX
        {
            get
            {
                return _ORDERINDEX;
            }
            set
            {
                OnORDERINDEXChanging(value);
                ReportPropertyChanging("ORDERINDEX");
                _ORDERINDEX = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ORDERINDEX");
                OnORDERINDEXChanged();
            }
        }
        private global::System.Int32 _ORDERINDEX;
        partial void OnORDERINDEXChanging(global::System.Int32 value);
        partial void OnORDERINDEXChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DOCMGModel", "RL_USER_MODULE", "TBUSER")]
        public EntityCollection<TBUSER> TBUSER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TBUSER>("DOCMGModel.RL_USER_MODULE", "TBUSER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TBUSER>("DOCMGModel.RL_USER_MODULE", "TBUSER", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DOCMGModel", Name="TBSYSCODE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBSYSCODE : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 TBSYSCODE 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="nAME">NAME 属性的初始值。</param>
        /// <param name="pARENTID">PARENTID 属性的初始值。</param>
        public static TBSYSCODE CreateTBSYSCODE(global::System.Int32 id, global::System.String nAME, global::System.Int32 pARENTID)
        {
            TBSYSCODE tBSYSCODE = new TBSYSCODE();
            tBSYSCODE.ID = id;
            tBSYSCODE.NAME = nAME;
            tBSYSCODE.PARENTID = pARENTID;
            return tBSYSCODE;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PARENTID
        {
            get
            {
                return _PARENTID;
            }
            set
            {
                OnPARENTIDChanging(value);
                ReportPropertyChanging("PARENTID");
                _PARENTID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PARENTID");
                OnPARENTIDChanged();
            }
        }
        private global::System.Int32 _PARENTID;
        partial void OnPARENTIDChanging(global::System.Int32 value);
        partial void OnPARENTIDChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DOCMGModel", "TBSYSCODETYPE_TBSYSCODE_FK1", "TBSYSCODETYPE")]
        public TBSYSCODETYPE TBSYSCODETYPE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBSYSCODETYPE>("DOCMGModel.TBSYSCODETYPE_TBSYSCODE_FK1", "TBSYSCODETYPE").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBSYSCODETYPE>("DOCMGModel.TBSYSCODETYPE_TBSYSCODE_FK1", "TBSYSCODETYPE").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TBSYSCODETYPE> TBSYSCODETYPEReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBSYSCODETYPE>("DOCMGModel.TBSYSCODETYPE_TBSYSCODE_FK1", "TBSYSCODETYPE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TBSYSCODETYPE>("DOCMGModel.TBSYSCODETYPE_TBSYSCODE_FK1", "TBSYSCODETYPE", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DOCMGModel", Name="TBSYSCODETYPE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBSYSCODETYPE : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 TBSYSCODETYPE 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static TBSYSCODETYPE CreateTBSYSCODETYPE(global::System.Int32 id)
        {
            TBSYSCODETYPE tBSYSCODETYPE = new TBSYSCODETYPE();
            tBSYSCODETYPE.ID = id;
            return tBSYSCODETYPE;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DOCMGModel", "TBSYSCODETYPE_TBSYSCODE_FK1", "TBSYSCODE")]
        public EntityCollection<TBSYSCODE> TBSYSCODE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TBSYSCODE>("DOCMGModel.TBSYSCODETYPE_TBSYSCODE_FK1", "TBSYSCODE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TBSYSCODE>("DOCMGModel.TBSYSCODETYPE_TBSYSCODE_FK1", "TBSYSCODE", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DOCMGModel", Name="TBUSER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBUSER : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 TBUSER 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="uSERID">USERID 属性的初始值。</param>
        /// <param name="uSERPWD">USERPWD 属性的初始值。</param>
        public static TBUSER CreateTBUSER(global::System.Int32 id, global::System.String uSERID, global::System.String uSERPWD)
        {
            TBUSER tBUSER = new TBUSER();
            tBUSER.ID = id;
            tBUSER.USERID = uSERID;
            tBUSER.USERPWD = uSERPWD;
            return tBUSER;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String USERNAME
        {
            get
            {
                return _USERNAME;
            }
            set
            {
                OnUSERNAMEChanging(value);
                ReportPropertyChanging("USERNAME");
                _USERNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("USERNAME");
                OnUSERNAMEChanged();
            }
        }
        private global::System.String _USERNAME;
        partial void OnUSERNAMEChanging(global::System.String value);
        partial void OnUSERNAMEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USERID
        {
            get
            {
                return _USERID;
            }
            set
            {
                OnUSERIDChanging(value);
                ReportPropertyChanging("USERID");
                _USERID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USERID");
                OnUSERIDChanged();
            }
        }
        private global::System.String _USERID;
        partial void OnUSERIDChanging(global::System.String value);
        partial void OnUSERIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USERPWD
        {
            get
            {
                return _USERPWD;
            }
            set
            {
                OnUSERPWDChanging(value);
                ReportPropertyChanging("USERPWD");
                _USERPWD = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USERPWD");
                OnUSERPWDChanged();
            }
        }
        private global::System.String _USERPWD;
        partial void OnUSERPWDChanging(global::System.String value);
        partial void OnUSERPWDChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DOCMGModel", "TBUSER_RL_USER_FIELD_FK1", "RL_USER_FIELD")]
        public EntityCollection<RL_USER_FIELD> RL_USER_FIELD
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RL_USER_FIELD>("DOCMGModel.TBUSER_RL_USER_FIELD_FK1", "RL_USER_FIELD");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RL_USER_FIELD>("DOCMGModel.TBUSER_RL_USER_FIELD_FK1", "RL_USER_FIELD", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DOCMGModel", "RL_USER_MODULE", "TBMODULE")]
        public EntityCollection<TBMODULE> TBMODULE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TBMODULE>("DOCMGModel.RL_USER_MODULE", "TBMODULE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TBMODULE>("DOCMGModel.RL_USER_MODULE", "TBMODULE", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
